"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";

export type UiLanguage = "en" | "te" | "ur";

const ENGLISH = {
  brandName: "JANASOOCHI",
  brandNative: "జనసూచి",
  brandSubtitle: "Electoral Roll Search & Verification",
  personalWorkspace: "Personal workspace",
  canonicalCount: "3,454 logical voters",
  partsScope: "Pallerlamudi · Parts 227–230",
  navSearch: "Search",
  navDocuments: "Documents",
  navReview: "Review",
  navDataQuality: "Data Quality",
  navDataInsights: "Data Insights",
  navAdministration: "Administration",
  logout: "Sign out",
  openMenu: "Open menu",
  closeMenu: "Close menu",
  languageLabel: "Interface language",
  english: "English",
  telugu: "తెలుగు",
  urdu: "اردو",
  urduBlockedTitle: "Urdu source data is not available",
  urduBlockedMessage:
    "Urdu ingestion remains blocked until valid source files beginning with %PDF- are supplied. No records will be synthesized from English or Telugu.",
  authorizedOnly: "Authorized access only",
  loginTitle: "Sign in to JANASOOCHI",
  loginLead: "Use the account issued by the administrator.",
  email: "Email address",
  password: "Password",
  signIn: "Sign in",
  signInPending: "Secure sign-in is ready for the Supabase Auth connection.",
  protectedNotice: "Voter records and source PDFs remain protected after sign-in.",
  pageSearchTitle: "Voter search",
  pageSearchLead: "Search one logical voter and view the matching source-language record.",
  pageDocumentsTitle: "Source documents",
  pageDocumentsLead: "Validate, process and resume authorized electoral-roll PDFs.",
  pageReviewTitle: "Review queue",
  pageReviewLead: "Resolve extraction and reconciliation issues without changing source evidence.",
  pageQualityTitle: "Data insights",
  pageQualityLead: "Explore real extraction, language, reconciliation and revision evidence without double-counting voters.",
  pageAdminTitle: "Administration",
  pageAdminLead: "Manage controlled access, security and audited exports.",
  sourceLanguage: "Source language",
  part: "Part",
  allSupportedParts: "All supported parts",
  name: "Name",
  relationName: "Relation name",
  relationType: "Relation type",
  houseNumber: "House number",
  age: "Age",
  gender: "Gender",
  epic: "EPIC / Voter ID",
  serial: "Serial number",
  allRelationTypes: "All relation types",
  father: "Father",
  mother: "Mother",
  husband: "Husband",
  guardian: "Guardian",
  other: "Other",
  unknown: "Unknown",
  allGenders: "All genders",
  male: "Male",
  female: "Female",
  thirdGender: "Third gender",
  searchButton: "Search records",
  clearFilters: "Clear filters",
  exactMatchHelp: "Part, Serial and EPIC use exact matching.",
  fuzzyMatchHelp: "Names, relation names and house numbers allow controlled fuzzy matching.",
  searchReady: "Filters are ready for the secure Supabase search adapter.",
  searchResults: "Search results",
  noResultsTitle: "No voter selected",
  noResultsText: "Enter one or more filters to search authorized source records.",
  resultLanguageRule: "The selected language always displays its own uploaded source record.",
  expectedRegister: "Approved register",
  logicalVoters: "Logical voters",
  supportedParts: "Supported parts",
  uploadPdf: "Select PDF",
  uploadAndValidate: "Upload and validate",
  selectedFile: "Selected file",
  noFileSelected: "No PDF selected",
  pdfOnly: "PDF only · Parts 227–230 · English or Telugu · Urdu blocked",
  uploadReady: "The file is ready for checksum and source validation.",
  invalidPdf: "Select a file with the .pdf extension.",
  adminAction: "Admin action",
  duplicateProtection: "Checksum duplicate protection",
  duplicateProtectionHelp: "Previously processed files are detected before new records are created.",
  resumableProcessing: "Page-level recovery",
  resumableProcessingHelp: "Failed pages and voter cards can resume without restarting the document.",
  languageDetection: "Source-language enforcement",
  languageDetectionHelp: "Records remain linked to the language of the uploaded source PDF.",
  uploadedDocuments: "Uploaded documents",
  documentsEmptyTitle: "No documents to display",
  documentsEmptyText: "Authorized source documents will appear here after the live query is connected.",
  filename: "Filename",
  pages: "Pages",
  records: "Records",
  status: "Status",
  uploaded: "Uploaded",
  actions: "Actions",
  urduIngestionStatus: "Urdu ingestion",
  blocked: "Blocked",
  severity: "Severity",
  critical: "Critical",
  needsReview: "Needs Review",
  informational: "Informational",
  allSeverities: "All severities",
  allStatuses: "All statuses",
  open: "Open",
  resolved: "Resolved",
  verified: "Verified",
  reviewItems: "Review items",
  reviewEmptyTitle: "No review item selected",
  reviewEmptyText: "Paginated, joined review rows will appear here when loaded.",
  issue: "Issue",
  voter: "Voter",
  pdfPage: "PDF page",
  confidence: "Confidence",
  action: "Action",
  reviewQueryNote: "Review data is fetched in small joined pages—never with oversized ID lists.",
  expected: "Expected",
  extracted: "Extracted",
  verifiedMetric: "Verified",
  languageCoverage: "Language coverage",
  liveValue: "Live value",
  awaitingLiveData: "Awaiting live data",
  completenessByPart: "Expected completeness by Part",
  dataQualityChecks: "Quality checks",
  missingSerials: "Missing serials",
  duplicateSerials: "Duplicate serials",
  suspiciousEpics: "Duplicate / suspicious EPICs",
  failedPages: "Failed pages",
  nullRates: "Field-null rates",
  reconciliationConflicts: "Reconciliation conflicts",
  qualityFilter: "Quality view",
  allLanguages: "All languages",
  englishSource: "English source",
  teluguSource: "Telugu source",
  urduSource: "Urdu source",
  expectedSourceCount: "Expected logical identities",
  actualValuesLive: "Extracted, verified and issue counts come only from Supabase.",
  accessControl: "Access control",
  accessControlHelp: "Admins manage users; Viewers have read-only access to permitted records.",
  addUser: "Add authorized user",
  bootstrapAdmin: "Controlled initial administrator",
  bootstrapAdminHelp: "Production signup never promotes the first public signup to Admin.",
  securityPosture: "Security posture",
  privateStorage: "Private PDF storage",
  rlsEnabled: "Row-level security",
  noServiceKey: "No service-role key in browser",
  leakedPasswordCheck: "Leaked-password protection review",
  auditedExports: "Audited dataset exports",
  exportCsv: "Export CSV",
  exportJson: "Export JSON",
  exportHelp: "Exports require Admin authorization and create an audit event.",
  userDirectory: "Authorized users",
  usersEmptyTitle: "No users to display",
  usersEmptyText: "Profiles and roles will appear here from the protected admin query.",
  role: "Role",
  lastActive: "Last active",
  operationNotConnected: "This control is ready for its protected server action.",
  part227: "Part 227",
  part228: "Part 228",
  part229: "Part 229",
  part230: "Part 230",
  refresh: "Refresh",
  notAvailable: "Not available in source PDF",
  requiresVerification: "Requires verification",
  noMatching: "No matching voter found",
  viewOriginalPage: "View original page",
  previous: "Previous",
  next: "Next",
  page: "Page",
  of: "of",
  printedPage: "Printed page",
  verification: "Verification status",
  matchScore: "Match score",
  loading: "Loading…",
  searchFailed: "Database temporarily unavailable. Please try the search again.",
  houseResults: "Voters listed under House Number",
} as const;

export type TranslationKey = keyof typeof ENGLISH;

const TELUGU: Partial<Record<TranslationKey, string>> = {
  brandSubtitle: "ఓటరు జాబితా శోధన & ధృవీకరణ",
  personalWorkspace: "వ్యక్తిగత కార్యస్థలం",
  canonicalCount: "3,454 తార్కిక ఓటర్లు",
  partsScope: "పల్లెర్లమూడి · భాగాలు 227–230",
  navSearch: "శోధన",
  navDocuments: "పత్రాలు",
  navReview: "సమీక్ష",
  navDataQuality: "డేటా నాణ్యత",
  navDataInsights: "డేటా అంతర్దృష్టులు",
  navAdministration: "నిర్వహణ",
  logout: "సైన్ అవుట్",
  openMenu: "మెను తెరవండి",
  closeMenu: "మెను మూసివేయండి",
  languageLabel: "ఇంటర్‌ఫేస్ భాష",
  urduBlockedTitle: "ఉర్దూ మూల డేటా అందుబాటులో లేదు",
  urduBlockedMessage: "%PDF- తో మొదలయ్యే చెల్లుబాటు అయ్యే మూల ఫైళ్లు అందే వరకు ఉర్దూ దిగుమతి నిలిపివేయబడింది. ఇంగ్లీష్ లేదా తెలుగు నుంచి రికార్డులు సృష్టించబడవు.",
  authorizedOnly: "అధీకృత ప్రవేశం మాత్రమే",
  loginTitle: "జనసూచికి సైన్ ఇన్ చేయండి",
  loginLead: "నిర్వాహకుడు ఇచ్చిన ఖాతాను ఉపయోగించండి.",
  email: "ఇమెయిల్ చిరునామా",
  password: "పాస్‌వర్డ్",
  signIn: "సైన్ ఇన్",
  signInPending: "సురక్షిత సైన్-ఇన్ Supabase Auth అనుసంధానానికి సిద్ధంగా ఉంది.",
  protectedNotice: "సైన్ ఇన్ తర్వాత ఓటరు రికార్డులు మరియు మూల PDFలు రక్షితంగా ఉంటాయి.",
  pageSearchTitle: "ఓటరు శోధన",
  pageSearchLead: "ఒక తార్కిక ఓటరును వెతికి, సరిపోలే మూల-భాష రికార్డును చూడండి.",
  pageDocumentsTitle: "మూల పత్రాలు",
  pageDocumentsLead: "అధీకృత ఓటరు జాబితా PDFలను ధృవీకరించండి, ప్రాసెస్ చేయండి మరియు కొనసాగించండి.",
  pageReviewTitle: "సమీక్ష వరుస",
  pageReviewLead: "మూల ఆధారాన్ని మార్చకుండా వెలికితీత మరియు సరిపోలిక సమస్యలను పరిష్కరించండి.",
  pageQualityTitle: "డేటా అంతర్దృష్టులు",
  pageQualityLead: "ఆమోదించిన 3,454 ఓటర్ల రిజిస్టర్‌తో సంపూర్ణతను కొలవండి.",
  pageAdminTitle: "నిర్వహణ",
  pageAdminLead: "నియంత్రిత ప్రవేశం, భద్రత మరియు ఆడిట్ చేసిన ఎగుమతులను నిర్వహించండి.",
  sourceLanguage: "మూల భాష",
  part: "భాగం",
  allSupportedParts: "అన్ని మద్దతు భాగాలు",
  name: "పేరు",
  relationName: "బంధువు పేరు",
  relationType: "బంధం రకం",
  houseNumber: "ఇంటి నంబర్",
  age: "వయస్సు",
  gender: "లింగం",
  epic: "EPIC / ఓటరు ID",
  serial: "క్రమ సంఖ్య",
  allRelationTypes: "అన్ని బంధం రకాలు",
  father: "తండ్రి",
  mother: "తల్లి",
  husband: "భర్త",
  guardian: "సంరక్షకుడు",
  other: "ఇతర",
  unknown: "తెలియదు",
  allGenders: "అన్ని లింగాలు",
  male: "పురుషుడు",
  female: "స్త్రీ",
  thirdGender: "తృతీయ లింగం",
  searchButton: "రికార్డులను వెతకండి",
  clearFilters: "ఫిల్టర్లను తొలగించండి",
  exactMatchHelp: "భాగం, క్రమ సంఖ్య మరియు EPIC ఖచ్చితంగా సరిపోలుతాయి.",
  fuzzyMatchHelp: "పేరు, బంధువు పేరు మరియు ఇంటి నంబర్ నియంత్రిత అస్పష్ట సరిపోలికను అనుమతిస్తాయి.",
  searchReady: "సురక్షిత Supabase శోధన కోసం ఫిల్టర్లు సిద్ధంగా ఉన్నాయి.",
  searchResults: "శోధన ఫలితాలు",
  noResultsTitle: "ఓటరు ఎంపిక కాలేదు",
  noResultsText: "అధీకృత మూల రికార్డులను వెతకడానికి ఒకటి లేదా ఎక్కువ ఫిల్టర్లు ఇవ్వండి.",
  resultLanguageRule: "ఎంచుకున్న భాష ఎల్లప్పుడూ అదే భాషలో అప్‌లోడ్ చేసిన మూల రికార్డును చూపుతుంది.",
  expectedRegister: "ఆమోదించిన రిజిస్టర్",
  logicalVoters: "తార్కిక ఓటర్లు",
  supportedParts: "మద్దతు భాగాలు",
  uploadPdf: "PDF ఎంచుకోండి",
  uploadAndValidate: "అప్‌లోడ్ చేసి ధృవీకరించండి",
  selectedFile: "ఎంచుకున్న ఫైల్",
  noFileSelected: "PDF ఎంపిక కాలేదు",
  pdfOnly: "PDF మాత్రమే · భాగాలు 227–230 · ఇంగ్లీష్ లేదా తెలుగు · ఉర్దూ నిలిపివేయబడింది",
  uploadReady: "ఫైల్ చెక్‌సమ్ మరియు మూల ధృవీకరణకు సిద్ధంగా ఉంది.",
  invalidPdf: ".pdf పొడిగింపుతో ఉన్న ఫైల్‌ను ఎంచుకోండి.",
  adminAction: "అడ్మిన్ చర్య",
  duplicateProtection: "చెక్‌సమ్ నకలు రక్షణ",
  duplicateProtectionHelp: "కొత్త రికార్డులు సృష్టించే ముందు ఇప్పటికే ప్రాసెస్ చేసిన ఫైళ్లు గుర్తించబడతాయి.",
  resumableProcessing: "పేజీ-స్థాయి పునరుద్ధరణ",
  resumableProcessingHelp: "పత్రాన్ని మళ్లీ మొదలుపెట్టకుండా విఫలమైన పేజీలు, ఓటరు కార్డులను కొనసాగించవచ్చు.",
  languageDetection: "మూల-భాష అమలు",
  languageDetectionHelp: "రికార్డులు అప్‌లోడ్ చేసిన మూల PDF భాషకే అనుసంధానంగా ఉంటాయి.",
  uploadedDocuments: "అప్‌లోడ్ చేసిన పత్రాలు",
  documentsEmptyTitle: "చూపించడానికి పత్రాలు లేవు",
  documentsEmptyText: "లైవ్ క్వెరీ అనుసంధానమైన తర్వాత అధీకృత మూల పత్రాలు ఇక్కడ కనిపిస్తాయి.",
  filename: "ఫైల్ పేరు",
  pages: "పేజీలు",
  records: "రికార్డులు",
  status: "స్థితి",
  uploaded: "అప్‌లోడ్ తేదీ",
  actions: "చర్యలు",
  urduIngestionStatus: "ఉర్దూ దిగుమతి",
  blocked: "నిలిపివేయబడింది",
  severity: "తీవ్రత",
  critical: "క్లిష్టమైనది",
  needsReview: "సమీక్ష అవసరం",
  informational: "సమాచారాత్మకం",
  allSeverities: "అన్ని తీవ్రతలు",
  allStatuses: "అన్ని స్థితులు",
  open: "తెరిచి ఉంది",
  resolved: "పరిష్కరించబడింది",
  verified: "ధృవీకరించబడింది",
  reviewItems: "సమీక్ష అంశాలు",
  reviewEmptyTitle: "సమీక్ష అంశం ఎంపిక కాలేదు",
  reviewEmptyText: "లోడ్ చేసినప్పుడు పేజీలుగా విభజించిన అనుసంధాన సమీక్ష వరుసలు ఇక్కడ కనిపిస్తాయి.",
  issue: "సమస్య",
  voter: "ఓటరు",
  pdfPage: "PDF పేజీ",
  confidence: "నమ్మకం",
  action: "చర్య",
  reviewQueryNote: "సమీక్ష డేటా చిన్న అనుసంధాన పేజీలలో వస్తుంది—పెద్ద ID జాబితాలతో కాదు.",
  expected: "అంచనా",
  extracted: "వెలికితీసినవి",
  verifiedMetric: "ధృవీకరించినవి",
  languageCoverage: "భాషా కవరేజ్",
  liveValue: "లైవ్ విలువ",
  awaitingLiveData: "లైవ్ డేటా కోసం వేచి ఉంది",
  completenessByPart: "భాగం వారీ అంచనా సంపూర్ణత",
  dataQualityChecks: "నాణ్యత తనిఖీలు",
  missingSerials: "లేని క్రమ సంఖ్యలు",
  duplicateSerials: "నకలు క్రమ సంఖ్యలు",
  suspiciousEpics: "నకలు / అనుమానాస్పద EPICలు",
  failedPages: "విఫలమైన పేజీలు",
  nullRates: "ఖాళీ ఫీల్డ్ రేట్లు",
  reconciliationConflicts: "సరిపోలిక విభేదాలు",
  qualityFilter: "నాణ్యత వీక్షణ",
  allLanguages: "అన్ని భాషలు",
  englishSource: "ఇంగ్లీష్ మూలం",
  teluguSource: "తెలుగు మూలం",
  urduSource: "ఉర్దూ మూలం",
  expectedSourceCount: "అంచనా తార్కిక గుర్తింపులు",
  actualValuesLive: "వెలికితీత, ధృవీకరణ మరియు సమస్యల సంఖ్యలు Supabase నుంచే వస్తాయి.",
  accessControl: "ప్రవేశ నియంత్రణ",
  accessControlHelp: "అడ్మిన్లు వినియోగదారులను నిర్వహిస్తారు; వీక్షకులకు అనుమతించిన రికార్డులపై చదవడానికి మాత్రమే ప్రవేశం ఉంటుంది.",
  addUser: "అధీకృత వినియోగదారుని జోడించండి",
  bootstrapAdmin: "నియంత్రిత మొదటి అడ్మిన్",
  bootstrapAdminHelp: "ప్రొడక్షన్ సైన్‌అప్ మొదటి పబ్లిక్ వినియోగదారుని అడ్మిన్‌గా మార్చదు.",
  securityPosture: "భద్రతా స్థితి",
  privateStorage: "ప్రైవేట్ PDF నిల్వ",
  rlsEnabled: "వరుస-స్థాయి భద్రత",
  noServiceKey: "బ్రౌజర్‌లో సర్వీస్-రోల్ కీ లేదు",
  leakedPasswordCheck: "లీకైన పాస్‌వర్డ్ రక్షణ సమీక్ష",
  auditedExports: "ఆడిట్ చేసిన డేటాసెట్ ఎగుమతులు",
  exportCsv: "CSV ఎగుమతి",
  exportJson: "JSON ఎగుమతి",
  exportHelp: "ఎగుమతులకు అడ్మిన్ అనుమతి అవసరం; ప్రతి ఎగుమతి ఆడిట్ ఈవెంట్‌ను సృష్టిస్తుంది.",
  userDirectory: "అధీకృత వినియోగదారులు",
  usersEmptyTitle: "చూపించడానికి వినియోగదారులు లేరు",
  usersEmptyText: "రక్షిత అడ్మిన్ క్వెరీ నుంచి ప్రొఫైళ్లు, పాత్రలు ఇక్కడ కనిపిస్తాయి.",
  role: "పాత్ర",
  lastActive: "చివరి క్రియాశీలత",
  operationNotConnected: "ఈ నియంత్రణ రక్షిత సర్వర్ చర్యకు సిద్ధంగా ఉంది.",
  refresh: "రిఫ్రెష్",
  notAvailable: "మూల PDFలో అందుబాటులో లేదు",
  requiresVerification: "ధృవీకరణ అవసరం",
  noMatching: "సరిపోలే ఓటరు కనబడలేదు",
  viewOriginalPage: "అసలు పేజీని చూడండి",
  previous: "మునుపటి",
  next: "తదుపరి",
  page: "పేజీ",
  of: "లో",
  printedPage: "ముద్రిత పేజీ",
  verification: "ధృవీకరణ స్థితి",
  matchScore: "సరిపోలిక స్కోర్",
  loading: "లోడ్ అవుతోంది…",
  searchFailed: "డేటాబేస్ తాత్కాలికంగా అందుబాటులో లేదు. మళ్లీ ప్రయత్నించండి.",
  houseResults: "ఇంటి నంబర్ కింద జాబితా చేసిన ఓటర్లు",
};

const URDU: Partial<Record<TranslationKey, string>> = {
  brandSubtitle: "انتخابی فہرست تلاش اور تصدیق",
  personalWorkspace: "ذاتی ورک اسپیس",
  canonicalCount: "۳٬۴۵۴ منطقی ووٹرز",
  partsScope: "پالرلامودی · حصے ۲۲۷–۲۳۰",
  navSearch: "تلاش",
  navDocuments: "دستاویزات",
  navReview: "جائزہ",
  navDataQuality: "ڈیٹا معیار",
  navDataInsights: "ڈیٹا بصیرت",
  navAdministration: "انتظامیہ",
  logout: "سائن آؤٹ",
  openMenu: "مینو کھولیں",
  closeMenu: "مینو بند کریں",
  languageLabel: "انٹرفیس زبان",
  urduBlockedTitle: "اردو ماخذ ڈیٹا دستیاب نہیں",
  urduBlockedMessage: "درست ماخذ فائلیں جو %PDF- سے شروع ہوں فراہم ہونے تک اردو درآمد بند ہے۔ انگریزی یا تلگو سے کوئی ریکارڈ تیار نہیں کیا جائے گا۔",
  authorizedOnly: "صرف مجاز رسائی",
  loginTitle: "JANASOOCHI میں سائن ان کریں",
  loginLead: "منتظم کی طرف سے جاری کردہ اکاؤنٹ استعمال کریں۔",
  email: "ای میل پتہ",
  password: "پاس ورڈ",
  signIn: "سائن ان",
  signInPending: "محفوظ سائن ان Supabase Auth کنکشن کے لیے تیار ہے۔",
  protectedNotice: "سائن ان کے بعد ووٹر ریکارڈ اور اصل PDFs محفوظ رہتے ہیں۔",
  pageSearchTitle: "ووٹر تلاش",
  pageSearchLead: "ایک منطقی ووٹر تلاش کریں اور متعلقہ ماخذ زبان کا ریکارڈ دیکھیں۔",
  pageDocumentsTitle: "ماخذ دستاویزات",
  pageDocumentsLead: "مجاز انتخابی فہرست PDFs کی توثیق، پراسیسنگ اور بحالی کریں۔",
  pageReviewTitle: "جائزہ قطار",
  pageReviewLead: "اصل ثبوت بدلے بغیر اخذ اور تطبیق کے مسائل حل کریں۔",
  pageQualityTitle: "ڈیٹا بصیرت",
  pageQualityLead: "منظور شدہ ۳٬۴۵۴ ووٹر رجسٹر کے مقابل مکمل ہونے کی پیمائش کریں۔",
  pageAdminTitle: "انتظامیہ",
  pageAdminLead: "کنٹرول شدہ رسائی، سکیورٹی اور آڈٹ شدہ برآمدات سنبھالیں۔",
  sourceLanguage: "ماخذ زبان",
  part: "حصہ",
  allSupportedParts: "تمام معاون حصے",
  name: "نام",
  relationName: "رشتہ دار کا نام",
  relationType: "رشتے کی قسم",
  houseNumber: "مکان نمبر",
  age: "عمر",
  gender: "جنس",
  epic: "EPIC / ووٹر آئی ڈی",
  serial: "سیریل نمبر",
  allRelationTypes: "تمام رشتے",
  father: "والد",
  mother: "والدہ",
  husband: "شوہر",
  guardian: "سرپرست",
  other: "دیگر",
  unknown: "نامعلوم",
  allGenders: "تمام اجناس",
  male: "مرد",
  female: "عورت",
  thirdGender: "تیسری جنس",
  searchButton: "ریکارڈ تلاش کریں",
  clearFilters: "فلٹر صاف کریں",
  exactMatchHelp: "حصہ، سیریل اور EPIC عین مطابق تلاش استعمال کرتے ہیں۔",
  fuzzyMatchHelp: "نام، رشتہ دار کے نام اور مکان نمبر میں محدود مبہم تلاش دستیاب ہے۔",
  searchReady: "فلٹر محفوظ Supabase تلاش کے لیے تیار ہیں۔",
  searchResults: "تلاش کے نتائج",
  noResultsTitle: "کوئی ووٹر منتخب نہیں",
  noResultsText: "مجاز ماخذ ریکارڈ تلاش کرنے کے لیے ایک یا زیادہ فلٹر درج کریں۔",
  resultLanguageRule: "منتخب زبان ہمیشہ اسی زبان میں اپ لوڈ شدہ اصل ریکارڈ دکھاتی ہے۔",
  expectedRegister: "منظور شدہ رجسٹر",
  logicalVoters: "منطقی ووٹرز",
  supportedParts: "معاون حصے",
  uploadPdf: "PDF منتخب کریں",
  uploadAndValidate: "اپ لوڈ اور تصدیق کریں",
  selectedFile: "منتخب فائل",
  noFileSelected: "کوئی PDF منتخب نہیں",
  pdfOnly: "صرف PDF · حصے ۲۲۷–۲۳۰ · انگریزی یا تلگو · اردو مسدود",
  uploadReady: "فائل چیک سم اور ماخذ کی توثیق کے لیے تیار ہے۔",
  invalidPdf: ".pdf ایکسٹینشن والی فائل منتخب کریں۔",
  adminAction: "ایڈمن کارروائی",
  duplicateProtection: "چیک سم نقل تحفظ",
  duplicateProtectionHelp: "نئے ریکارڈ بنانے سے پہلے پہلے سے پراسیس شدہ فائلوں کی شناخت ہوتی ہے۔",
  resumableProcessing: "صفحہ سطح بحالی",
  resumableProcessingHelp: "دستاویز دوبارہ شروع کیے بغیر ناکام صفحات اور ووٹر کارڈ بحال کیے جا سکتے ہیں۔",
  languageDetection: "ماخذ زبان کا نفاذ",
  languageDetectionHelp: "ریکارڈ اپ لوڈ شدہ اصل PDF کی زبان سے منسلک رہتے ہیں۔",
  uploadedDocuments: "اپ لوڈ شدہ دستاویزات",
  documentsEmptyTitle: "دکھانے کے لیے کوئی دستاویز نہیں",
  documentsEmptyText: "لائیو استفسار جڑنے کے بعد مجاز ماخذ دستاویزات یہاں نظر آئیں گی۔",
  filename: "فائل نام",
  pages: "صفحات",
  records: "ریکارڈ",
  status: "حالت",
  uploaded: "اپ لوڈ تاریخ",
  actions: "کارروائیاں",
  urduIngestionStatus: "اردو درآمد",
  blocked: "بند",
  severity: "شدت",
  critical: "سنگین",
  needsReview: "جائزہ درکار",
  informational: "معلوماتی",
  allSeverities: "تمام شدتیں",
  allStatuses: "تمام حالتیں",
  open: "کھلا",
  resolved: "حل شدہ",
  verified: "تصدیق شدہ",
  reviewItems: "جائزہ اشیاء",
  reviewEmptyTitle: "کوئی جائزہ شے منتخب نہیں",
  reviewEmptyText: "لوڈ ہونے پر صفحہ وار مربوط جائزہ قطاریں یہاں دکھائی جائیں گی۔",
  issue: "مسئلہ",
  voter: "ووٹر",
  pdfPage: "PDF صفحہ",
  confidence: "اعتماد",
  action: "کارروائی",
  reviewQueryNote: "جائزہ ڈیٹا چھوٹے مربوط صفحات میں آتا ہے—بڑی ID فہرستوں میں نہیں۔",
  expected: "متوقع",
  extracted: "اخذ شدہ",
  verifiedMetric: "تصدیق شدہ",
  languageCoverage: "زبان کوریج",
  liveValue: "لائیو قدر",
  awaitingLiveData: "لائیو ڈیٹا کا انتظار",
  completenessByPart: "حصہ وار متوقع تکمیل",
  dataQualityChecks: "معیار جانچ",
  missingSerials: "غائب سیریلز",
  duplicateSerials: "نقل سیریلز",
  suspiciousEpics: "نقل / مشتبہ EPICs",
  failedPages: "ناکام صفحات",
  nullRates: "خالی فیلڈ شرح",
  reconciliationConflicts: "تطبیق تنازعات",
  qualityFilter: "معیار منظر",
  allLanguages: "تمام زبانیں",
  englishSource: "انگریزی ماخذ",
  teluguSource: "تلگو ماخذ",
  urduSource: "اردو ماخذ",
  expectedSourceCount: "متوقع منطقی شناختیں",
  actualValuesLive: "اخذ، تصدیق اور مسئلہ شمار صرف Supabase سے آتے ہیں۔",
  accessControl: "رسائی کنٹرول",
  accessControlHelp: "ایڈمن صارفین سنبھالتے ہیں؛ ناظرین صرف مجاز ریکارڈ پڑھ سکتے ہیں۔",
  addUser: "مجاز صارف شامل کریں",
  bootstrapAdmin: "کنٹرول شدہ ابتدائی ایڈمن",
  bootstrapAdminHelp: "پروڈکشن سائن اپ پہلے عوامی صارف کو ایڈمن نہیں بناتا۔",
  securityPosture: "سکیورٹی حالت",
  privateStorage: "نجی PDF اسٹوریج",
  rlsEnabled: "قطار سطح سکیورٹی",
  noServiceKey: "براؤزر میں سروس رول کلید نہیں",
  leakedPasswordCheck: "لیک پاس ورڈ تحفظ جائزہ",
  auditedExports: "آڈٹ شدہ ڈیٹاسیٹ برآمدات",
  exportCsv: "CSV برآمد",
  exportJson: "JSON برآمد",
  exportHelp: "برآمد کے لیے ایڈمن اجازت ضروری ہے اور آڈٹ واقعہ بنتا ہے۔",
  userDirectory: "مجاز صارفین",
  usersEmptyTitle: "دکھانے کے لیے کوئی صارف نہیں",
  usersEmptyText: "محفوظ ایڈمن استفسار سے پروفائل اور کردار یہاں نظر آئیں گے۔",
  role: "کردار",
  lastActive: "آخری سرگرمی",
  operationNotConnected: "یہ کنٹرول محفوظ سرور کارروائی کے لیے تیار ہے۔",
  refresh: "تازہ کریں",
  notAvailable: "ماخذ PDF میں دستیاب نہیں",
  requiresVerification: "تصدیق درکار ہے",
  noMatching: "کوئی مماثل ووٹر نہیں ملا",
  viewOriginalPage: "اصل صفحہ دیکھیں",
  previous: "پچھلا",
  next: "اگلا",
  page: "صفحہ",
  of: "از",
  printedPage: "مطبوعہ صفحہ",
  verification: "تصدیقی حالت",
  matchScore: "مماثلت اسکور",
  loading: "لوڈ ہو رہا ہے…",
  searchFailed: "ڈیٹابیس عارضی طور پر دستیاب نہیں۔ دوبارہ کوشش کریں۔",
  houseResults: "مکان نمبر کے تحت درج ووٹر",
};

const TRANSLATIONS: Record<UiLanguage, Partial<Record<TranslationKey, string>>> = {
  en: ENGLISH,
  te: TELUGU,
  ur: URDU,
};

interface LanguageContextValue {
  language: UiLanguage;
  setLanguage: (language: UiLanguage) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);
const STORAGE_KEY = "janasoochi-ui-language";

function isUiLanguage(value: string | null): value is UiLanguage {
  return value === "en" || value === "te" || value === "ur";
}

export function LanguageProvider({ children }: Readonly<{ children: ReactNode }>) {
  const [language, setLanguage] = useState<UiLanguage>("en");
  const [ready, setReady] = useState(false);

  useEffect(() => {
    const storedLanguage = window.localStorage.getItem(STORAGE_KEY);
    if (isUiLanguage(storedLanguage)) setLanguage(storedLanguage);
    setReady(true);
  }, []);

  useEffect(() => {
    const root = document.documentElement;
    root.lang = language === "te" ? "te-IN" : language === "ur" ? "ur-IN" : "en-IN";
    root.dir = language === "ur" ? "rtl" : "ltr";
    if (ready) window.localStorage.setItem(STORAGE_KEY, language);
  }, [language, ready]);

  const t = useCallback(
    (key: TranslationKey) => TRANSLATIONS[language][key] ?? ENGLISH[key],
    [language],
  );

  const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
