export type Role='admin'|'viewer';
export type RecordLanguage='en'|'te'|'ur';
export type BoundingBox={x:number;y:number;width:number;height:number;pageWidth:number;pageHeight:number};
export type FieldConfidence=Partial<Record<'name'|'relation_name'|'house_number'|'age'|'gender'|'epic'|'serial_number',number>>;
export interface Voter{id:string;pdf_id:string;logical_voter_id:string|null;part_number:number;serial_number:string|null;original_name:string|null;normalized_name:string|null;transliterated_name:string|null;relation_type:'Father'|'Mother'|'Husband'|'Guardian'|'Other'|'Unknown';original_relation_name:string|null;normalized_relation_name:string|null;transliterated_relation_name:string|null;original_house_number:string|null;normalized_house_number:string|null;age:number|null;gender:string|null;epic_number:string|null;pdf_page_number:number;printed_page_number:number|null;original_text:string;original_language:RecordLanguage|null;ocr_confidence:number|null;field_confidence:FieldConfidence;name_confidence:number|null;relation_confidence:number|null;house_confidence:number|null;age_confidence:number|null;epic_confidence:number|null;bounding_box:BoundingBox|null;verification_status:'verified'|'requires_review'|'unverified';possible_duplicate:boolean;duplicate_of:string|null;corrected_value?:Record<string,string>|null}
export interface DocumentRow{id:string;filename:string;part_number:number;total_pdf_pages:number;processed_pages:number;failed_pages:number;records_count:number;processing_status:string;uploaded_at:string;updated_at:string;completed_at:string|null;storage_path:string;checksum:string;source_language:RecordLanguage;detected_language:RecordLanguage|null;language_confidence:number|null;expected_voter_total:number|null;review_records:number;revision_identifier:string|null;active_version:boolean;supersedes_id:string|null}
export interface PageRow{id:number;pdf_id:string;pdf_page_number:number;printed_page_number:number|null;status:string;page_type:'cover'|'summary'|'map'|'voter'|'unknown';ocr_confidence:number|null;records_detected:number;records_extracted:number;review_records:number;dropped_records:number;issue_detail:string|null;error_type:string|null;error_message:string|null;detected_language:RecordLanguage|null;language_confidence:number|null;retry_count:number;processed_at:string|null;updated_at:string;created_at:string}
export type AgeTolerance=0|1|2|3;
export interface Filters{part:string;name:string;father:string;husband:string;mother:string;house:string;age:string;ageTolerance:AgeTolerance;gender:string;epic:string;serial:string;fuzzy:boolean;recordLanguage:RecordLanguage;selectedLanguageOnly:boolean}
export interface LanguageCoverage{source_language:RecordLanguage;logical_total:number;source_records:number;linked_records:number;unlinked_records:number;unavailable_records:number}
export interface MatchExplanation{field:string;detail:string;score:number;kind:'exact'|'partial'|'transliteration'|'fuzzy'|'tolerance'}
export interface SearchHit{record:Voter;matchScore:number|null;matchType:'Exact Match'|'Partial Match'|'Transliteration Match'|'Fuzzy Match'|null;explanation:MatchExplanation[]}
